package org.aksw.databugger.tests;

import com.hp.hpl.jena.query.*;
import com.hp.hpl.jena.rdf.model.RDFNode;
import org.aksw.databugger.Utils;
import org.aksw.databugger.enums.TestGeneration;
import org.aksw.databugger.patterns.Pattern;
import org.aksw.databugger.patterns.PatternParameter;
import org.aksw.databugger.patterns.PatternService;
import org.aksw.databugger.sources.Source;

import java.util.ArrayList;
import java.util.List;
/**
 * User: Dimitris Kontokostas
 * Takes a sparqlPattern and a SPARQL query and based on the data
 * returned from that query we generate test cases
 * Created: 9/20/13 2:48 PM
 */
public class TestAutoGenerator {
    final public String URI;
    final public String description;
    final public String query;
    final public String patternID;

    public TestAutoGenerator(String uri, String description, String query, String patternID) {
        this.URI = uri;
        this.description = description;
        this.query = query;
        this.patternID = patternID;
    }

    public List<UnitTest> generate(Source source) {
        List<UnitTest> tests = new ArrayList<UnitTest>();

        Query q = QueryFactory.create(Utils.getAllPrefixes() + query);
        QueryExecution qe = source.getExecutionFactory().createQueryExecution(q);
        ResultSet rs = qe.execSelect();
        Pattern pattern = PatternService.getPattern(patternID);

        while (rs.hasNext()) {
            QuerySolution row = rs.next();

            List<String> bindings = new ArrayList<String>();
            for (PatternParameter p : pattern.parameters) {
                if (row.contains(p.id)) {
                    RDFNode n = row.get(p.id);
                    if (n.isResource())
                        bindings.add("<" + n.toString() + ">");
                    else
                        bindings.add(n.toString());
                } else {
                    break;
                }


            }

            try {
                String sparql = pattern.instantiateSparqlPattern(bindings);
                String sparqlPrev = pattern.instantiateSparqlPatternPrevalence(bindings);
                tests.add(new UnitTest(
                        patternID,
                        TestGeneration.AutoGenerated,
                        this.URI,
                        source.getSourceType(),
                        source.uri,
                        new TestAnnotation(),
                        sparql,
                        sparqlPrev));
            } catch (Exception e) {

            }

        }


        return tests;
    }
}
