PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT COUNT(*)
WHERE {
    ?s rdf:type foaf:Person .
    FILTER NOT EXISTS {?s rdf:type dbo:Person}
}
