# This query finds all multiple values for release date, where attributes 
# of release dates are missing, or better not yet extracted.
# 
# All instances with multiple values for release date that miss attributes:

prefix dbpedia-prop: <http://dbpedia.org/property/>
select ?s count(?c) {
  ?s dbpedia-prop:released ?c.
}
GROUP BY ?s
HAVING count(?c) > 1