# This query finds all the yago classes having two successive capital letters
# following a lower case letter. Not all of these class names are really
# broken since e.g.
# <http://dbpedia.org/class/yago/4th-centuryBCPoets> or 
# <http://dbpedia.org/class/yago/6th-centuryBCRulers> were apparently really
# ment to have two successive capital letters. Some of such resources (but not
# all) are provided in the white list, given in the SPARQL query below.
#
# Since this query uses a double regex and DISTINCT it is very slow (as one
# would expect). But I couldn't figure out a better way to retrieve all these
# classes.
#
# See http://www.mail-archive.com/dbpedia-discussion@lists.sourceforge.net/msg02790.html
# for details.

SELECT DISTINCT ?yagoClass
WHERE {
    ?s rdf:type ?yagoClass.
    FILTER (
        regex(?yagoClass, "[a-z][A-Z][A-Z]")
        && regex(?yagoClass, "^http://dbpedia.org/class/yago/") 
        && ?yagoClass NOT IN (
            <http://dbpedia.org/class/yago/4th-centuryBCPhilosophers> ,
            <http://dbpedia.org/class/yago/6th-centuryBCGreekPeople> ,
            <http://dbpedia.org/class/yago/9th-centuryBCBiblicalRulers> ,
            <http://dbpedia.org/class/yago/UnixSUS2008Utilities> ,
            <http://dbpedia.org/class/yago/6th-centuryBCRulers> ,
            <http://dbpedia.org/class/yago/4th-centuryBCPoets> ,
            <http://dbpedia.org/class/yago/1st-centuryBCPhilosophers> ,
            <http://dbpedia.org/class/yago/5th-centuryBCMilitaryAlliances> ,
            <http://dbpedia.org/class/yago/8th-centuryBCWomen> ,
            <http://dbpedia.org/class/yago/PopulatedPlacesEstablishedInThe4thCenturyBC> ,
            <http://dbpedia.org/class/yago/GeoclassSeatOfAThird-orderAdministrativeDivision> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingJapan> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingItaly> ,
            <http://dbpedia.org/class/yago/WorldWarIIAerialOperationsAndBattlesOfTheEasternFront> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingRomania> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingHungary> ,
            <http://dbpedia.org/class/yago/1st-millenniumBCBooks> ,
            <http://dbpedia.org/class/yago/FilmsWithACapitalPunishmentTheme> ,
            <http://dbpedia.org/class/yago/AtariSTGames> ,
            <http://dbpedia.org/class/yago/AppleIIGames> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingTheUnitedKingdom> ,
            <http://dbpedia.org/class/yago/NavalBattlesOfWorldWarIIInvolvingCanada> ,
            <http://dbpedia.org/class/yago/1st-centuryBCPoets> ,
            <http://dbpedia.org/class/yago/BritishRadioDJs> ,
            <http://dbpedia.org/class/yago/NintendoDSGames> ,
            <http://dbpedia.org/class/yago/CharactersInBookVIOfTheAeneid> ,
            <http://dbpedia.org/class/yago/WivesOfHenryVIII> ,
            <http://dbpedia.org/class/yago/BattlesAndOperationsOfWorldWarIIInvolvingGermany> ,
            <http://dbpedia.org/class/yago/SerieAManagers> ,
            <http://dbpedia.org/class/yago/CategoryCPrisonsInEngland> ,
            <http://dbpedia.org/class/yago/MilitaryUnitsAndFormationsOfGermanyInWorldWarII> ,
            <http://dbpedia.org/class/yago/WorldWarIIBritishBombers> ,
            <http://dbpedia.org/class/yago/2nd-centuryBCPoets> ,
            <http://dbpedia.org/class/yago/7th-centuryBCERulers> ,
            <http://dbpedia.org/class/yago/WorldWarIPrisonersOfWarHeldByItaly> ,
            <http://dbpedia.org/class/yago/SerieBFootballers> ,
            <http://dbpedia.org/class/yago/Children&#39;sITVTelevisionProgrammes> ,
            <http://dbpedia.org/class/yago/Children'sITVTelevisionProgrammes> ,
            <http://dbpedia.org/class/yago/BattlesOfWorldWarIIInvolvingGermany> ,
            <http://dbpedia.org/class/yago/UnitedStatesNavyPilotsOfWorldWarII> ,
            <http://dbpedia.org/class/yago/LigaIPlayers> ,
            <http://dbpedia.org/class/yago/EnglandBInternationalFootballers> ,
            <http://dbpedia.org/class/yago/OperasWithAMythologicalSetting> ,
            <http://dbpedia.org/class/yago/WorldWarIIPrisonersOfWarHeldByTheUnitedStates> ,
            <http://dbpedia.org/class/yago/8th-centuryBCPoets> ,
            <http://dbpedia.org/class/yago/WorldWarIBattleshipsOfItaly> ,
            <http://dbpedia.org/class/yago/WorldWarIIAircraftCarriersOfTheUnitedKingdom> ,
            <http://dbpedia.org/class/yago/JailedUKPeers> ,
            <http://dbpedia.org/class/yago/WorldWarIIDiveBombers> ,
            <http://dbpedia.org/class/yago/CroatianPeopleOfWorldWarII> ,
            <http://dbpedia.org/class/yago/DanishPeopleOfWorldWarII> ,
            <http://dbpedia.org/class/yago/WorldWarIIInfantryWeapons> ,
            <http://dbpedia.org/class/yago/PopulatedPlacesEstablishedInThe1stCenturyBC> ,
            <http://dbpedia.org/class/yago/WebBrowsersForDOS> ,
            <http://dbpedia.org/class/yago/FrenchCiviliansKilledInWorldWarII> ,
            <http://dbpedia.org/class/yago/ScummVMSupportedGames> ,
            <http://dbpedia.org/class/yago/PopulatedPlacesEstablishedInThe7thMillenniumBC> ,
            <http://dbpedia.org/class/yago/WorldWarIISovietInfantryWeapons> ,
            <http://dbpedia.org/class/yago/PrisonersAtADXFlorence> ,
            <http://dbpedia.org/class/yago/CurrentFBITenMostWantedFugitives> ,
            <http://dbpedia.org/class/yago/6th-centuryBCPeople> ,
            <http://dbpedia.org/class/yago/WorldWarIIResistanceMovements> ,
            <http://dbpedia.org/class/yago/PolishPeopleOfWorldWarII> ,
            <http://dbpedia.org/class/yago/CardinalsCreatedByPopePiusXII> ,
            <http://dbpedia.org/class/yago/GradeIListedGovernmentBuildings> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInCambridgeshire> ,
            <http://dbpedia.org/class/yago/PopulatedPlacesEstablishedInThe8thCenturyBC> ,
            <http://dbpedia.org/class/yago/BattlesAndOperationsOfWorldWarIIInvolvingIndia> ,
            <http://dbpedia.org/class/yago/FilmsFeaturingABestDramaActressGoldenGlobeWinningPerformance> ,
            <http://dbpedia.org/class/yago/FilmsFeaturingABestActressAcademyAwardWinningPerformance> ,
            <http://dbpedia.org/class/yago/WorldWarITreaties> ,
            <http://dbpedia.org/class/yago/UnitedStatesMarineCorpsPilotsOfWorldWarII> ,
            <http://dbpedia.org/class/yago/NavalBattlesOfWorldWarIIInvolvingNewZealand> ,
            <http://dbpedia.org/class/yago/SouthAtlanticConvoysOfWorldWarII> ,
            <http://dbpedia.org/class/yago/WorldWarIIShipwrecksInThePacificOcean> ,
            <http://dbpedia.org/class/yago/WorldWarIIGuidedMissilesOfGermany> ,
            <http://dbpedia.org/class/yago/WorldWarIISpiesForGermany> ,
            <http://dbpedia.org/class/yago/WorldWarIIOperationsAndBattlesOfTheItalianCampaign> ,
            <http://dbpedia.org/class/yago/MajorLeaguEBaseballPitchers> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInLondon> ,
            <http://dbpedia.org/class/yago/PresidentsOfSurreyCCC> ,
            <http://dbpedia.org/class/yago/WeaklyNP-completeProblems> ,
            <http://dbpedia.org/class/yago/RomanianPeopleOfWorldWarII> ,
            <http://dbpedia.org/class/yago/1st-centuryBCWorks> ,
            <http://dbpedia.org/class/yago/WorldWarIHistoryBooks> ,
            <http://dbpedia.org/class/yago/WorldWarIIOccupiedTerritories> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInCheshire> ,
            <http://dbpedia.org/class/yago/GrandMastersOfTheUGLE> ,
            <http://dbpedia.org/class/yago/MacOSXE-mailClients> ,
            <http://dbpedia.org/class/yago/RoyalAirForceWorldWarIIAirMarshals> ,
            <http://dbpedia.org/class/yago/StatesAndTerritoriesEstablishedInThe3rdMillenniumBC> ,
            <http://dbpedia.org/class/yago/WorldWarIIPassengerShipsOfGermany> ,
            <http://dbpedia.org/class/yago/CanadianLGBT-relatedTelevisionPrograms> ,
            <http://dbpedia.org/class/yago/GradeIListedMonasteries> ,
            <http://dbpedia.org/class/yago/AustralianWorldWarIIPilots> ,
            <http://dbpedia.org/class/yago/ConcurrentWarsToWorldWarII> ,
            <http://dbpedia.org/class/yago/UniversitiesAndCollegesAffiliatedWithTheAmericanBaptistChurchesUSA> ,
            <http://dbpedia.org/class/yago/NorthAtlanticConvoysOfWorldWarII> ,
            <http://dbpedia.org/class/yago/NavalBattlesOfWorldWarIIInvolvingFrance> ,
            <http://dbpedia.org/class/yago/NavalBattlesOfWorldWarIIInvolvingPoland> ,
            <http://dbpedia.org/class/yago/AustrianWorldWarIPoets> ,
            <http://dbpedia.org/class/yago/RadioProgramsOnXMRadio> ,
            <http://dbpedia.org/class/yago/NavalBattlesOfWorldWarIIInvolvingAustralia> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInNorthYorkshire> ,
            <http://dbpedia.org/class/yago/WorldWarIIGhettos> ,
            <http://dbpedia.org/class/yago/CompaniesListedOnTASE> ,
            <http://dbpedia.org/class/yago/AlumniOfINSEAD> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInNorfolk> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInNorthumberland> ,
            <http://dbpedia.org/class/yago/WorldWarIIBritishInfantryWeapons> ,
            <http://dbpedia.org/class/yago/WorldWarIIFirearmsOfTheUnitedStates> ,
            <http://dbpedia.org/class/yago/WorldWarIIAmericanInfantryWeapons> ,
            <http://dbpedia.org/class/yago/WorldWarIIGermanInfantryWeapons> ,
            <http://dbpedia.org/class/yago/WorldWarIITrialsFilms> ,
            <http://dbpedia.org/class/yago/3rd-centuryBCFemaleRulers> ,
            <http://dbpedia.org/class/yago/BritishLGBT-relatedTelevisionProgrammes> ,
            <http://dbpedia.org/class/yago/10th-centuryBCPeopl> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInBristol> ,
            <http://dbpedia.org/class/yago/GradeIListedLibraryBuildings> ,
            <http://dbpedia.org/class/yago/4th-centuryBCWomen> ,
            <http://dbpedia.org/class/yago/9th-centuryBCFemaleRuler> ,
            <http://dbpedia.org/class/yago/BritishCiviliansKilledInWorldWarII> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInOxford> ,
            <http://dbpedia.org/class/yago/GovernmentsInExileDuringWorldWarII> ,
            <http://dbpedia.org/class/yago/SpainBInternationalFootballers> ,
            <http://dbpedia.org/class/yago/PartsOfATheatre> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInWorcestershire> ,
            <http://dbpedia.org/class/yago/BattlesAndOperationsOfWorldWarIIInvolvingTheUnitedKingdom> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInSomerset> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInGlouCEstershire> ,
            <http://dbpedia.org/class/yago/GradeIListedBuildingsInLincolnshire> ,
            <http://dbpedia.org/class/yago/ArticleITribunals> ,
            <http://dbpedia.org/class/yago/WorldWarIShipwrecksInTheNorthSea> ,
            <http://dbpedia.org/class/yago/PolishResistanceFightersOfWorldWarII> ,
            <http://dbpedia.org/class/yago/NintendoDSRPGGames> ,
            <http://dbpedia.org/class/yago/WindowsXPTypefaces> ,
            <http://dbpedia.org/class/yago/PopulatedPlacesEstablishedInThe2ndCenturyBC> ,
            <http://dbpedia.org/class/yago/WorldWarIISuBmarinesOfFrance>
        )
    )
}
