#!/usr/bin/perl
if ( "-f" ~~ @argv ){
	system ("java", "-jar", "/etc/share/java/rdfunit/*.jar", @argv);
	print("a");
} else {
	push (@argv, "-f");
	push (@argv, "~/.rdfunit");
	if (! (-d "$ENV{HOME}/.rdfunit")){
		print("Creating rdfunit dir under ~/.rdfunit\n");
		$ok=mkdir("$ENV{HOME}/rdfunit",0777);
		print "$!\n" if ($ok == 0);
		print ("Copying data to ~/.rdfunit\n");
		system("cp","-r","/etc/share/java/rdfunit/data/","$ENV{HOME}/.rdfunit/");
	}
	system ("java", "-jar", "/etc/share/java/rdfunit/rdfunit-core.jar", @argv);

}
