package org.aksw.rdfunit.tests.executors;

import org.aksw.rdfunit.Utils.CacheUtils;
import org.aksw.rdfunit.Utils.TestUtils;
import org.aksw.rdfunit.enums.TestGenerationType;
import org.aksw.rdfunit.exceptions.TripleReaderException;
import org.aksw.rdfunit.io.DataReaderFactory;
import org.aksw.rdfunit.io.RDFFileReader;
import org.aksw.rdfunit.io.RDFFileWriter;
import org.aksw.rdfunit.sources.SchemaSource;
import org.aksw.rdfunit.sources.Source;
import org.aksw.rdfunit.tests.TestAutoGenerator;
import org.aksw.rdfunit.tests.TestCase;
import org.aksw.rdfunit.tests.TestSuite;
import org.aksw.rdfunit.tests.executors.monitors.TestGeneratorExecutorMonitor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;


/**
 * User: Dimitris Kontokostas
 * handles test generation form a schema or a cache
 * Created: 11/20/13 7:31 PM
 */
public class TestGeneratorExecutor {
    private static final Logger log = LoggerFactory.getLogger(TestGeneratorExecutor.class);
    private boolean isCanceled = false;
    private final boolean loadFromCache;
    private final boolean useManualTests;

    public TestGeneratorExecutor() {
        this.loadFromCache = true;
        this.useManualTests = true;
    }

    public TestGeneratorExecutor(boolean loadFromCache, boolean useManualTests) {
        this.loadFromCache = loadFromCache;
        this.useManualTests = useManualTests;
    }

    private final java.util.Collection<TestGeneratorExecutorMonitor> progressMonitors = new ArrayList<TestGeneratorExecutorMonitor>();


    public void cancel() {
        isCanceled = true;
    }


    public TestSuite generateTestSuite(String testFolder, Source dataset, java.util.Collection<TestAutoGenerator> autoGenerators) {

        java.util.Collection<SchemaSource> sources = dataset.getReferencesSchemata();


        /*notify start of testing */
        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.generationStarted(dataset, sources.size());
        }

        java.util.Collection<TestCase> allTests = new ArrayList<TestCase>();
        for (SchemaSource s : sources) {
            if (isCanceled) {
                break;
            }

            log.info("Generating tests for: " + s.getUri());

            //Generate auto tests from schema
            allTests.addAll(generateAutoTestsForSchemaSource(testFolder, s, autoGenerators));

            //Find manual tests for schema
            if (useManualTests)
                allTests.addAll(generateManualTestsForSource(testFolder, s));
        }

        //Find manual tests for dataset (if not canceled
        if (!isCanceled && useManualTests)
            allTests.addAll(generateManualTestsForSource(testFolder, dataset));

        /*notify start of testing */
        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.generationFinished();
        }

        return new TestSuite(allTests);
    }

    private java.util.Collection<TestCase> generateAutoTestsForSchemaSource(String testFolder, SchemaSource s, java.util.Collection<TestAutoGenerator> autoGenerators) {
        java.util.Collection<TestCase> tests = new ArrayList<TestCase>();

        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.sourceGenerationStarted(s, TestGenerationType.AutoGenerated);
        }

        try {
            String cachedTestsLocation = CacheUtils.getSourceAutoTestFile(testFolder, s);
            if (!loadFromCache)
                cachedTestsLocation = ""; // non existing path
            java.util.Collection<TestCase> testsAutoCached = TestUtils.instantiateTestsFromModel(
                    new RDFFileReader(cachedTestsLocation).read());
            tests.addAll(testsAutoCached);
            log.info(s.getUri() + " contains " + testsAutoCached.size() + " automatically created tests (loaded from cache)");

        } catch (TripleReaderException e) {
            // cannot read from file  / generate
            java.util.Collection<TestCase> testsAuto = TestUtils.instantiateTestsFromAG(autoGenerators, s);
            tests.addAll(testsAuto);
            TestUtils.writeTestsToFile(testsAuto, new RDFFileWriter(CacheUtils.getSourceAutoTestFile(testFolder, s)));
            log.info(s.getUri() + " contains " + testsAuto.size() + " automatically created tests");
        }

        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.sourceGenerationExecuted(s, TestGenerationType.AutoGenerated, tests.size());
        }

        return tests;
    }

    private java.util.Collection<TestCase> generateManualTestsForSource(String testFolder, Source s) {
        java.util.Collection<TestCase> tests = new ArrayList<TestCase>();

        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.sourceGenerationStarted(s, TestGenerationType.ManuallyGenerated);
        }
        try {
            java.util.Collection<TestCase> testsManuals = TestUtils.instantiateTestsFromModel(
                    DataReaderFactory.createFileOrResourceTripleReader(
                            CacheUtils.getSourceManualTestFile(testFolder, s),                 // check for local directory first
                            CacheUtils.getSourceManualTestFile("/org/aksw/rdfunit/tests/", s)  // otherwise check if it exists in resources
                    ).read());

            tests.addAll(testsManuals);
            log.info(s.getUri() + " contains " + testsManuals.size() + " manually created tests");
        } catch (TripleReaderException e) {
            // Do nothing, Manual tests do not exist
        }

        for (TestGeneratorExecutorMonitor monitor : progressMonitors) {
            monitor.sourceGenerationExecuted(s, TestGenerationType.ManuallyGenerated, tests.size());
        }

        return tests;


    }


    public void addTestExecutorMonitor(TestGeneratorExecutorMonitor monitor) {
        progressMonitors.add(monitor);
    }

    public void removeTestExecutorMonitor(TestGeneratorExecutorMonitor monitor) {
        progressMonitors.remove(monitor);
    }
}
