PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.property/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX georss: <http://www.georss.org/georss/>

SELECT COUNT(*) {
    ?s geo:lat ?lat .
    ?s geo:long ?long .
    ?s georss:point ?point.
    FILTER (?point != fn:concat(?lat, ' ', ?long))
}
