PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT COUNT(*) {
    ?s dbp:dateOfBirth ?o .
    FILTER NOT EXISTS {?s dbo:birthDate ?bd}
}
