package org.aksw.databugger.enums;

/**
 * User: Dimitris Kontokostas
 * Describes the test generation methods
 * Created: 9/25/13 9:05 AM
 */
public enum TestGeneration {

    /**
     * AutoGenerated: This test was created automatically
     * */
    AutoGenerated,

    /**
     * ManuallyGenerated: This test was created manually
     * */
    ManuallyGenerated;

    public String getUri() {
        // TODO make prefix configurable
        return "http://databugger.aksw.org/ontology/" + name();
    }

    @Override
    public String toString() {
        return getUri();
    }
}
